/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author LUIS LEITON
 */
public class VistaDoctor extends javax.swing.JFrame {

    /**
     * Creates new form VistaDoctor
     */
    public VistaDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnCancelarCita = new javax.swing.JButton();
    btnAtenderCita = new javax.swing.JButton();
    btnCitasRegistradas = new javax.swing.JButton();
    btnDiagnosticos = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    btnAsignarCita = new javax.swing.JButton();
    btnTratamientos = new javax.swing.JButton();
    btnCantidadCitas = new javax.swing.JButton();
    btnCantidadDiagnosticos = new javax.swing.JButton();
    btnCantidadTratamientos = new javax.swing.JButton();
    btnDetalleHospitalizaciones = new javax.swing.JButton();
    btnVolver = new javax.swing.JButton();
    btnSeguimientoInternado = new javax.swing.JButton();
    btnRDiagnosticos = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnCancelarCita.setBackground(new java.awt.Color(0, 102, 102));
    btnCancelarCita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnCancelarCita.setText("Cancelar cita");
    btnCancelarCita.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarCitaActionPerformed(evt);
      }
    });

    btnAtenderCita.setBackground(new java.awt.Color(0, 102, 102));
    btnAtenderCita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnAtenderCita.setText("Atender cita");
    btnAtenderCita.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAtenderCitaActionPerformed(evt);
      }
    });

    btnCitasRegistradas.setBackground(new java.awt.Color(0, 102, 102));
    btnCitasRegistradas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnCitasRegistradas.setText("Citas registradas");
    btnCitasRegistradas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCitasRegistradasActionPerformed(evt);
      }
    });

    btnDiagnosticos.setBackground(new java.awt.Color(0, 102, 102));
    btnDiagnosticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnDiagnosticos.setText("Diagnósticos ");
    btnDiagnosticos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDiagnosticosActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 153, 153));
    jLabel3.setText("Bienvenido");

    btnAsignarCita.setBackground(new java.awt.Color(0, 102, 102));
    btnAsignarCita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnAsignarCita.setText("Asignar cita");
    btnAsignarCita.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAsignarCitaActionPerformed(evt);
      }
    });

    btnTratamientos.setBackground(new java.awt.Color(0, 102, 102));
    btnTratamientos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnTratamientos.setText("Tratamientos");
    btnTratamientos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTratamientosActionPerformed(evt);
      }
    });

    btnCantidadCitas.setBackground(new java.awt.Color(0, 102, 102));
    btnCantidadCitas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnCantidadCitas.setText("Cantidad de citas");
    btnCantidadCitas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCantidadCitasActionPerformed(evt);
      }
    });

    btnCantidadDiagnosticos.setBackground(new java.awt.Color(0, 102, 102));
    btnCantidadDiagnosticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnCantidadDiagnosticos.setText("Cantidad de diagnósticos");

    btnCantidadTratamientos.setBackground(new java.awt.Color(0, 102, 102));
    btnCantidadTratamientos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnCantidadTratamientos.setText("Cantidad de tratamientos");

    btnDetalleHospitalizaciones.setBackground(new java.awt.Color(0, 102, 102));
    btnDetalleHospitalizaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnDetalleHospitalizaciones.setText("Detalle de hospitalizaciones");
    btnDetalleHospitalizaciones.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDetalleHospitalizacionesActionPerformed(evt);
      }
    });

    btnVolver.setBackground(new java.awt.Color(0, 102, 102));
    btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnVolver.setText("Volver");
    btnVolver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVolverActionPerformed(evt);
      }
    });

    btnSeguimientoInternado.setBackground(new java.awt.Color(0, 102, 102));
    btnSeguimientoInternado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnSeguimientoInternado.setText("Seguimiento Internado");
    btnSeguimientoInternado.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSeguimientoInternadoActionPerformed(evt);
      }
    });

    btnRDiagnosticos.setBackground(new java.awt.Color(0, 102, 102));
    btnRDiagnosticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnRDiagnosticos.setText("Registrar Diagnósticos");
    btnRDiagnosticos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRDiagnosticosActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGap(333, 333, 333)
            .addComponent(jLabel3))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(btnAsignarCita)
              .addComponent(btnTratamientos))
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addComponent(btnCantidadCitas)
                .addGap(33, 33, 33)
                .addComponent(btnCantidadDiagnosticos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCantidadTratamientos))
              .addGroup(layout.createSequentialGroup()
                .addComponent(btnCancelarCita)
                .addGap(36, 36, 36)
                .addComponent(btnAtenderCita)
                .addGap(33, 33, 33)
                .addComponent(btnCitasRegistradas)
                .addGap(56, 56, 56)
                .addComponent(btnDiagnosticos))))
          .addGroup(layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(136, 136, 136))
              .addGroup(layout.createSequentialGroup()
                .addComponent(btnDetalleHospitalizaciones)
                .addGap(37, 37, 37)
                .addComponent(btnSeguimientoInternado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRDiagnosticos)
                .addGap(40, 40, 40)))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnAsignarCita)
              .addComponent(btnCancelarCita)
              .addComponent(btnAtenderCita)
              .addComponent(btnCitasRegistradas)
              .addComponent(btnDiagnosticos))
            .addGap(32, 32, 32)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnTratamientos)
              .addComponent(btnCantidadCitas)
              .addComponent(btnCantidadDiagnosticos)
              .addComponent(btnCantidadTratamientos))
            .addGap(92, 92, 92))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnDetalleHospitalizaciones)
              .addComponent(btnSeguimientoInternado)
              .addComponent(btnRDiagnosticos))
            .addGap(30, 30, 30)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
        .addComponent(btnVolver)
        .addGap(44, 44, 44))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCitaActionPerformed

    }//GEN-LAST:event_btnCancelarCitaActionPerformed

    private void btnAsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCitaActionPerformed
        
    }//GEN-LAST:event_btnAsignarCitaActionPerformed

    private void btnAtenderCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderCitaActionPerformed

    }//GEN-LAST:event_btnAtenderCitaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSeguimientoInternadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguimientoInternadoActionPerformed

    }//GEN-LAST:event_btnSeguimientoInternadoActionPerformed

    private void btnCitasRegistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasRegistradasActionPerformed
   
    }//GEN-LAST:event_btnCitasRegistradasActionPerformed

    private void btnDiagnosticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticosActionPerformed

    }//GEN-LAST:event_btnDiagnosticosActionPerformed

    private void btnTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientosActionPerformed

    }//GEN-LAST:event_btnTratamientosActionPerformed

    private void btnDetalleHospitalizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleHospitalizacionesActionPerformed

    }//GEN-LAST:event_btnDetalleHospitalizacionesActionPerformed

    private void btnRDiagnosticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRDiagnosticosActionPerformed

    }//GEN-LAST:event_btnRDiagnosticosActionPerformed

  private void btnCantidadCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadCitasActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCantidadCitasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaDoctor().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnAsignarCita;
  public javax.swing.JButton btnAtenderCita;
  public javax.swing.JButton btnCancelarCita;
  public javax.swing.JButton btnCantidadCitas;
  public javax.swing.JButton btnCantidadDiagnosticos;
  public javax.swing.JButton btnCantidadTratamientos;
  public javax.swing.JButton btnCitasRegistradas;
  public javax.swing.JButton btnDetalleHospitalizaciones;
  public javax.swing.JButton btnDiagnosticos;
  public javax.swing.JButton btnRDiagnosticos;
  public javax.swing.JButton btnSeguimientoInternado;
  public javax.swing.JButton btnTratamientos;
  public javax.swing.JButton btnVolver;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
}
