/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author LUIS LEITON
 */
public class VistaEnfermero extends javax.swing.JFrame {

    /**
     * Creates new form VistaEnfermero
     */
    public VistaEnfermero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetalleHospitalizaciones = new javax.swing.JButton();
        btnCancelarCita = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCitasRegistradas = new javax.swing.JButton();
        btnDiagnosticos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAsignarCita = new javax.swing.JButton();
        btnTratamientos = new javax.swing.JButton();
        btnCantidadCitas = new javax.swing.JButton();
        btnCantidadDiagnosticos = new javax.swing.JButton();
        btnCantidadTratamientos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDetalleHospitalizaciones.setBackground(new java.awt.Color(0, 102, 102));
        btnDetalleHospitalizaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetalleHospitalizaciones.setText("Detalle de hospitalizaciones");

        btnCancelarCita.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelarCita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelarCita.setText("Cancelar cita");
        btnCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCitaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(0, 102, 102));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCitasRegistradas.setBackground(new java.awt.Color(0, 102, 102));
        btnCitasRegistradas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCitasRegistradas.setText("Citas registradas");

        btnDiagnosticos.setBackground(new java.awt.Color(0, 102, 102));
        btnDiagnosticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDiagnosticos.setText("Diagnósticos ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Bienvenido");

        btnAsignarCita.setBackground(new java.awt.Color(0, 102, 102));
        btnAsignarCita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAsignarCita.setText("Asignar cita");
        btnAsignarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCitaActionPerformed(evt);
            }
        });

        btnTratamientos.setBackground(new java.awt.Color(0, 102, 102));
        btnTratamientos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTratamientos.setText("Tratamientos");

        btnCantidadCitas.setBackground(new java.awt.Color(0, 102, 102));
        btnCantidadCitas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCantidadCitas.setText("Cantidad de citas");

        btnCantidadDiagnosticos.setBackground(new java.awt.Color(0, 102, 102));
        btnCantidadDiagnosticos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCantidadDiagnosticos.setText("Cantidad de diagnósticos");

        btnCantidadTratamientos.setBackground(new java.awt.Color(0, 102, 102));
        btnCantidadTratamientos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCantidadTratamientos.setText("Cantidad de tratamientos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCantidadCitas)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnAsignarCita)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelarCita)
                                .addGap(34, 34, 34)
                                .addComponent(btnCitasRegistradas)
                                .addGap(18, 18, 18)
                                .addComponent(btnDiagnosticos)
                                .addGap(18, 18, 18)
                                .addComponent(btnTratamientos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnCantidadDiagnosticos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolver)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCantidadTratamientos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDetalleHospitalizaciones)))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarCita)
                    .addComponent(btnCancelarCita)
                    .addComponent(btnCitasRegistradas)
                    .addComponent(btnDiagnosticos)
                    .addComponent(btnTratamientos))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCantidadCitas)
                    .addComponent(btnCantidadDiagnosticos)
                    .addComponent(btnCantidadTratamientos)
                    .addComponent(btnDetalleHospitalizaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCitaActionPerformed
        CancelarCitaEnfermero CCE = new CancelarCitaEnfermero();
        CCE.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnCancelarCitaActionPerformed

    private void btnAsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCitaActionPerformed

    }//GEN-LAST:event_btnAsignarCitaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
      Principal P = new Principal();
      P.setVisible(true);

      this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEnfermero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEnfermero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEnfermero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEnfermero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEnfermero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAsignarCita;
    public javax.swing.JButton btnCancelarCita;
    public javax.swing.JButton btnCantidadCitas;
    public javax.swing.JButton btnCantidadDiagnosticos;
    public javax.swing.JButton btnCantidadTratamientos;
    public javax.swing.JButton btnCitasRegistradas;
    public javax.swing.JButton btnDetalleHospitalizaciones;
    public javax.swing.JButton btnDiagnosticos;
    public javax.swing.JButton btnTratamientos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
